version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: budget_tracker_db
    restart: always
    environment:
      POSTGRES_DB: budget_tracker
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: